name: LensArt by Rex
favicon: null
layout_spectrum: 0.6987236684653908
typography_spectrum: 0.46505575627088547
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#faf8fd'
    - '#2a3233'
    - '#535739'
    - '#8f8d5f'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
