name: LensArt by Rex
favicon: null
layout_spectrum: 0.6987236684653908
typography_spectrum: 0.46505575627088547
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#8f0017'
    - '#000000'
    - '#99353e'
    - '#8b8b8b'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
